Repository UDIGO2/U_DIGO, pull requests merged in 2025-03, with the labels that each got.

#1 feat/insert
  .gradle/8.12.1/fileHashes/fileHashes.bin
  .gradle/8.12.1/fileHashes/fileHashes.lock
  .idea/.name
  src/main/java/com/ohgiraffers/udigo/crud/menu/controller/MenuController.java
  src/main/java/com/ohgiraffers/udigo/crud/menu/model/dao/MenuMapper.java
  src/main/java/com/ohgiraffers/udigo/crud/menu/model/service/MenuService.java
  src/main/resources/mappers/MenuMapper.xml
  src/main/resources/templates/menu/regist.html
Labels: enhancement

#2 feat/update
  src/main/java/com/ohgiraffers/udigo/crud/menu/controller/MenuController.java
  src/main/java/com/ohgiraffers/udigo/crud/menu/model/dao/MenuMapper.java
  src/main/java/com/ohgiraffers/udigo/crud/menu/model/service/MenuService.java
  src/main/resources/mappers/MenuMapper.xml
  src/main/resources/templates/menu/detail.html
  src/main/resources/templates/menu/edit.html
Labels: bug

#6 feat/update
  src/main/java/com/ohgiraffers/udigo/crud/configuration/Chap08CrudApplication.java
  src/main/java/com/ohgiraffers/udigo/crud/menu/model/service/MenuService.java
  src/main/resources/application.yaml
  src/main/resources/mappers/MenuMapper.xml
  src/main/resources/static/index.html
  src/main/resources/templates/menu/detail.html
Labels: wontfix
